name: codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@master
      with:
        go-version: 1.17

    - name: Generate Coverage Report
      run: go test ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.txt
