name: codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  codecov:
    name: codecov
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.19.x, 1.20.x ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Generate Coverage Report
      run: go test ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
