name: Build
on:
  - push
  - pull_request
jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        go: [ 1.20.x ]
    runs-on:
      - ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: make all

      - name: Test
        run: make tests
