name: Test
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on:
      - ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.19"

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: make all

    - name: Test
      run: make tests
